# APP Config og Server
spring.application.name=AiProject
server.port=8080

# Database (MySQL i Docker på 127.0.0.1:3307)
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/aiproject?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Copenhagen
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.datasource.url=${URL}
#spring.datasource.username=${USERNAME}
# spring.datasource.password=${PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Groq API nøgle
groq.api.key=${GROQ_API_KEY}
# Vi kan eventuel lave samme setup som Ronnis chatgptjokes med model, temp, token bla bla etc.

# Logging - Viser SQL og HTTP-requests i terminalen
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.example.aiproject=DEBUG

